"""Manage the curated source allowlist: load it, read publishers' terms, list the state, sign or reject.

Spec §4 (rights), §5 (fetch allowlist). Four subcommands, run in this order the first time:

    load      read fixtures/source-policies/*.yaml into source_policy
    capture   fetch each publisher's terms page, store the text and its hash
    list      show every publisher and what it is waiting for
    sign      record that a rights reviewer read the captured terms and accepted them

`capture` is the one that needs internet access, and it is why this is a script and not a migration: it runs on a
GitHub runner or on the server, not in the environment where the policy files were written.

Nothing here can make a domain fetchable by itself. `source_policy.effective` is generated by the database and
requires a signature over the exact terms text on record, so a publisher that quietly changes its licence stops
being readable without anyone having to notice.

    uv run python scripts/source_policies.py load
    uv run python scripts/source_policies.py capture
    uv run python scripts/source_policies.py list
    uv run python scripts/source_policies.py sign --domain medlineplus.gov --reviewer lead@clinic.example
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from datetime import UTC, datetime
from typing import Any

import httpx
import psycopg
from moveai_db import J, connect
from moveai_ingestion.parse import parse_html
from moveai_ingestion.source_policies import PolicyError, load_publishers, reject, sign, sync
from psycopg.rows import dict_row

CAPTURE_TIMEOUT_S = 30
MAX_TERMS_BYTES = 4 * 1024 * 1024
QUOTE_CHARS = 600


def terms_text(content: bytes) -> str:
    """The licence terms as text, normalised so that presentation changes are not read as licence changes.

    Hashing the raw bytes would flag a new cookie banner or a rotated analytics tag as a change of terms, and a
    re-verification prompt that cries wolf is one nobody reads. Hashing extracted, whitespace-normalised text
    means the hash moves when the words move.
    """
    doc = parse_html(content)
    return re.sub(r"\s+", " ", doc.text()).strip()


def capture_one(client: httpx.Client, pol: dict[str, Any]) -> dict[str, Any]:
    """Fetch one publisher's terms page. Returns the evidence fields to store; never raises for a bad site."""
    try:
        resp = client.get(pol["policy_reference"])
    except httpx.HTTPError as e:
        return {"state": "unreachable", "evidence": {"error": f"{type(e).__name__}: {e}", "attempted_at": datetime.now(UTC).isoformat()}}
    if resp.status_code != 200:
        # Name the status. The first real run reported these as "0 chars", which reads like an empty page and sent
        # the diagnosis straight past the actual cause — a 403 (the site refuses unknown clients) and a 404 (the
        # URL in the policy file is simply wrong) need completely different fixes, and neither is "0 chars".
        meaning = {
            403: "the site refused this client",
            404: "no such page — the policy_reference URL is wrong",
            429: "rate limited; try again later",
        }.get(resp.status_code, "")
        return {
            "state": "unreachable",
            "evidence": {
                "http_status": resp.status_code,
                "final_url": str(resp.url),
                "error": f"HTTP {resp.status_code}" + (f" — {meaning}" if meaning else ""),
                "attempted_at": datetime.now(UTC).isoformat(),
            },
        }
    content = resp.content[:MAX_TERMS_BYTES]
    text = terms_text(content)
    if len(text) < 200:
        # A terms page that extracts to nothing is almost always a JavaScript shell or a consent interstitial.
        # Signing that would be signing a blank page.
        return {
            "state": "unreachable",
            "evidence": {
                "http_status": resp.status_code,
                "final_url": str(resp.url),
                "error": f"only {len(text)} characters of text; the page is probably rendered client-side",
                "attempted_at": datetime.now(UTC).isoformat(),
            },
        }
    return {
        "state": "captured",
        "evidence": {
            "sha256": hashlib.sha256(text.encode()).hexdigest(),
            "fetched_at": datetime.now(UTC).isoformat(),
            "http_status": resp.status_code,
            "final_url": str(resp.url),
            "text_chars": len(text),
            "quoted_span": text[:QUOTE_CHARS],
        },
    }


def cmd_capture(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    rows = conn.execute(
        "select * from source_policy where (%s::text is null or domain=%s) order by publisher",
        (args.domain, args.domain),
    ).fetchall()
    if not rows:
        print("no policies to capture; run `load` first", file=sys.stderr)
        return 2

    drifted = 0
    with httpx.Client(
        follow_redirects=True,
        timeout=CAPTURE_TIMEOUT_S,
        headers={"User-Agent": "MoveAI-Ingest/0.1 (licence terms verification; allowlist only)"},
    ) as client:
        for pol in rows:
            out = capture_one(client, pol)
            state = out["state"]
            new_sha = out["evidence"].get("sha256")
            # Drift is not just "different from last time" — it is "different from what someone signed". That is
            # the comparison that matters, and the one that must be loud.
            if state == "captured" and pol["signed_evidence_sha256"] and new_sha != pol["signed_evidence_sha256"]:
                state = "drifted"
                drifted += 1
            conn.execute(
                "update source_policy set evidence=%s, evidence_state=%s where id=%s",
                (J(out["evidence"]), state, pol["id"]),
            )
            detail = out["evidence"].get("error") or f"{out['evidence'].get('text_chars', 0)} chars"
            print(f"  {state:<11} {pol['domain']:<28} {detail}")

    conn.commit()
    if drifted:
        print(f"\n{drifted} publisher(s) changed their terms since they were signed. They are no longer readable.")
        print("Read the new terms and sign again, or reject them.")
    return 0


def cmd_load(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    result = sync(conn, load_publishers())
    conn.commit()
    for key in ("added", "updated", "unchanged"):
        if result[key]:
            print(f"  {key}: {', '.join(result[key])}")
    if result["orphaned"]:
        print(f"\n  in the database but not in the files (left alone): {', '.join(result['orphaned'])}")
    print("\nNothing is readable yet. Run `capture` to read each publisher's terms, then `sign` to accept them.")
    return 0


def cmd_list(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    rows = conn.execute("select * from source_policy order by effective desc, publisher").fetchall()
    if not rows:
        print("no policies loaded; run `load` first")
        return 0
    print(f"{'DOMAIN':<28} {'LICENCE':<26} {'TERMS':<11} {'REVIEW':<9} READABLE")
    for r in rows:
        print(
            f"{r['domain']:<28} {r['license_id']:<26} {r['evidence_state']:<11} {r['review_state']:<9} {'yes' if r['effective'] else 'no'}"
        )
    readable = sum(1 for r in rows if r["effective"])
    print(f"\n{readable} of {len(rows)} publishers can be read.")
    if readable < len(rows):
        waiting = [r["domain"] for r in rows if r["review_state"] == "pending" and r["evidence_state"] == "captured"]
        if waiting:
            print(f"Waiting for a rights reviewer to sign: {', '.join(waiting)}")
    return 0


def _reviewer_id(conn: psycopg.Connection, email: str) -> Any:
    row = conn.execute("select id, roles::text[] as roles from app_user where lower(email)=lower(%s)", (email,)).fetchone()
    if not row:
        raise PolicyError(f"no user {email!r}. Invite them first with scripts/invite.py.")
    if not ({"rights_reviewer", "clinical_lead"} & set(row["roles"] or [])):
        raise PolicyError(
            f"{email} holds [{', '.join(row['roles'] or []) or 'no roles'}]; signing licence terms needs rights_reviewer or clinical_lead"
        )
    return row["id"]


def cmd_sign(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    try:
        if args.reject and not args.note:
            raise PolicyError("rejecting a publisher needs --note saying why; an unexplained refusal gets re-proposed next quarter")
        reviewer = _reviewer_id(conn, args.reviewer)
        row = reject(conn, args.domain, reviewer, args.note) if args.reject else sign(conn, args.domain, reviewer, args.note)
    except PolicyError as e:
        conn.rollback()
        print(f"refused: {e}", file=sys.stderr)
        return 2
    conn.commit()
    verb = "rejected" if args.reject else "signed"
    print(f"{verb} {row['domain']} ({row['publisher']}, {row['license_id']}) by {args.reviewer}")
    if not args.reject:
        print(f"readable: {'yes' if row['effective'] else 'no'}")
        if not row["effective"]:
            print(f"  the licence permits can_fetch={row['can_fetch']}, so this publisher still cannot be read.")
        print(f"  next review: {row['next_review_at']:%Y-%m-%d}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Manage the curated source allowlist.")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("load", help="read the policy files into the database")

    cap = sub.add_parser("capture", help="fetch each publisher's terms page and record it (needs internet access)")
    cap.add_argument("--domain", default=None, help="just this one")

    sub.add_parser("list", help="show every publisher and what it is waiting for")

    sg = sub.add_parser("sign", help="accept or reject a publisher's captured terms")
    sg.add_argument("--domain", required=True)
    sg.add_argument("--reviewer", required=True, help="email of a rights_reviewer or clinical_lead")
    sg.add_argument("--note", default=None, help="recorded with the decision")
    sg.add_argument("--reject", action="store_true", help="record a decision not to use this publisher")

    args = ap.parse_args(argv)
    handlers = {"load": cmd_load, "capture": cmd_capture, "list": cmd_list, "sign": cmd_sign}
    with connect() as conn:
        conn.row_factory = dict_row
        return handlers[args.cmd](conn, args)


if __name__ == "__main__":
    sys.exit(main())
