"""Manage the curated source allowlist: load it, read publishers' terms, list the state, sign or reject.

Spec §4 (rights), §5 (fetch allowlist). Four subcommands, run in this order the first time:

    load      read fixtures/source-policies/*.yaml into source_policy
    capture   fetch each publisher's terms page, store the text and its hash
    list      show every publisher and what it is waiting for
    sign      record that a rights reviewer read the captured terms and accepted them

`capture` is the one that needs internet access, and it is why this is a script and not a migration: it runs on a
GitHub runner or on the server, not in the environment where the policy files were written.

Nothing here can make a domain fetchable by itself. `source_policy.effective` is generated by the database and
requires a signature over the exact terms text on record, so a publisher that quietly changes its licence stops
being readable without anyone having to notice.

    uv run python scripts/source_policies.py load
    uv run python scripts/source_policies.py capture
    uv run python scripts/source_policies.py list
    uv run python scripts/source_policies.py sign --domain medlineplus.gov --reviewer lead@clinic.example
"""

from __future__ import annotations

import argparse
import sys
from typing import Any

import httpx
import psycopg
from moveai_db import connect
from moveai_ingestion.source_policies import (
    CAPTURE_HEADERS as HTTP_HEADERS,
)
from moveai_ingestion.source_policies import (
    CAPTURE_TIMEOUT_S,
    PolicyError,
    capture_terms,
    load_publishers,
    record_capture,
    reject,
    sign,
    sync,
)
from psycopg.rows import dict_row
from selectolax.parser import HTMLParser

# Words that appear in a link to a terms, licence or copyright page. Used only to *suggest* candidates to a human;
# nothing here picks a policy_reference on its own.
TERMS_HINTS = ("terms", "copyright", "licence", "license", "usage", "reuse", "rights", "disclaimer", "policies", "policy")


def capture_one(client: httpx.Client, pol: dict[str, Any]) -> dict[str, Any]:
    """Kept as a name the tests use; the work lives in moveai_ingestion.source_policies."""
    return capture_terms(pol["policy_reference"], client)


def cmd_find_terms(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    """List candidate terms pages for publishers whose policy_reference did not resolve.

    Every 404 in the first real capture was a policy_reference I had guessed rather than looked up, and guessing a
    second time from the same position would be no better. This fetches the publisher's home page and reports the
    links that look like terms, licence or copyright pages, so the URL that goes into publishers.yaml is one that
    was actually found on their site.

    It suggests; it never selects. Nothing here writes to source_policy, and a person still has to put the URL in
    the file and read what it says.
    """
    rows = conn.execute(
        "select * from source_policy where (%s::text is null or domain=%s) order by publisher",
        (args.domain, args.domain),
    ).fetchall()
    if not rows:
        print("no policies loaded; run `load` first", file=sys.stderr)
        return 2
    if not args.all:
        rows = [r for r in rows if r["evidence_state"] != "captured"]
        if not rows:
            print("every publisher's terms have been captured; nothing to look for. Use --all to list anyway.")
            return 0

    with httpx.Client(follow_redirects=True, timeout=CAPTURE_TIMEOUT_S, headers=HTTP_HEADERS) as client:
        for pol in rows:
            print(f"\n{pol['publisher']} ({pol['domain']})")
            print(f"  currently pointing at: {pol['policy_reference']}  -> {(pol['evidence'] or {}).get('error', 'not tried')}")
            try:
                resp = client.get(f"https://{pol['domain']}/")
            except httpx.HTTPError as e:
                print(f"  home page unreachable too: {type(e).__name__}: {e}")
                continue
            if resp.status_code != 200:
                print(f"  home page returned HTTP {resp.status_code}; this publisher refuses automated access")
                continue

            seen: dict[str, str] = {}
            for a in HTMLParser(resp.text).css("a[href]"):
                href = (a.attributes.get("href") or "").strip()
                label = " ".join(a.text(strip=True).split())[:60]
                if not href or href.startswith(("#", "mailto:", "javascript:")):
                    continue
                if not any(h in href.lower() or h in label.lower() for h in TERMS_HINTS):
                    continue
                absolute = str(httpx.URL(str(resp.url)).join(href))
                # Only pages the publisher itself serves: a link out to creativecommons.org is the licence, not
                # this publisher's statement that they use it.
                if (httpx.URL(absolute).host or "").lower() != pol["domain"]:
                    continue
                seen.setdefault(absolute.split("#")[0], label or "(no link text)")
            if not seen:
                print("  no candidate links found on the home page; the terms may be reachable only from a footer menu")
            for url, label in sorted(seen.items())[:12]:
                print(f"    {url}\n        {label}")
    print("\nPut the right URL in fixtures/source-policies/publishers.yaml, then run `capture` again.")
    return 0


def cmd_capture(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    # Sync from the files first, always. capture fetches whatever policy_reference is sitting in the database, so
    # a policy_reference edited in publishers.yaml but never `load`ed would capture the OLD url and report it as
    # unreachable again, giving no sign that the fix was never applied. This happened: two URLs were corrected in
    # a PR, `capture` was run straight after merging, and it silently re-fetched the stale ones. sync() is
    # idempotent and never touches a signature unless the file actually changed, so running it here has no cost
    # when nothing changed and closes the gap when something did.
    result = sync(conn)
    conn.commit()
    if result["updated"]:
        print(f"  synced from publishers.yaml first: {', '.join(result['updated'])} changed")

    rows = conn.execute(
        "select * from source_policy where (%s::text is null or domain=%s) order by publisher",
        (args.domain, args.domain),
    ).fetchall()
    if not rows:
        print("no policies to capture; run `load` first", file=sys.stderr)
        return 2

    drifted = 0
    with httpx.Client(
        follow_redirects=True,
        timeout=CAPTURE_TIMEOUT_S,
        headers=HTTP_HEADERS,
    ) as client:
        for pol in rows:
            out = capture_one(client, pol)
            row = record_capture(conn, pol, out)
            if row["evidence_state"] == "drifted":
                drifted += 1
            detail = out["evidence"].get("error") or f"{out['evidence'].get('text_chars', 0)} chars"
            print(f"  {row['evidence_state']:<11} {pol['domain']:<28} {detail}")

    conn.commit()
    if drifted:
        print(f"\n{drifted} publisher(s) changed their terms since they were signed. They are no longer readable.")
        print("Read the new terms and sign again, or reject them.")
    return 0


def cmd_load(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    result = sync(conn, load_publishers())
    conn.commit()
    for key in ("added", "updated", "unchanged"):
        if result[key]:
            print(f"  {key}: {', '.join(result[key])}")
    if result["orphaned"]:
        print(f"\n  in the database but not in the files (left alone): {', '.join(result['orphaned'])}")
    print("\nNothing is readable yet. Run `capture` to read each publisher's terms, then `sign` to accept them.")
    return 0


def cmd_list(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    rows = conn.execute("select * from source_policy order by effective desc, publisher").fetchall()
    if not rows:
        print("no policies loaded; run `load` first")
        return 0
    print(f"{'DOMAIN':<28} {'LICENCE':<26} {'TERMS':<11} {'REVIEW':<9} READABLE")
    for r in rows:
        print(
            f"{r['domain']:<28} {r['license_id']:<26} {r['evidence_state']:<11} {r['review_state']:<9} {'yes' if r['effective'] else 'no'}"
        )
    readable = sum(1 for r in rows if r["effective"])
    print(f"\n{readable} of {len(rows)} publishers can be read.")
    if readable < len(rows):
        waiting = [r["domain"] for r in rows if r["review_state"] == "pending" and r["evidence_state"] == "captured"]
        if waiting:
            print(f"Waiting for a rights reviewer to sign: {', '.join(waiting)}")
    return 0


def _reviewer_id(conn: psycopg.Connection, email: str) -> Any:
    row = conn.execute("select id, roles::text[] as roles from app_user where lower(email)=lower(%s)", (email,)).fetchone()
    if not row:
        raise PolicyError(f"no user {email!r}. Invite them first with scripts/invite.py.")
    if not ({"rights_reviewer", "clinical_lead"} & set(row["roles"] or [])):
        raise PolicyError(
            f"{email} holds [{', '.join(row['roles'] or []) or 'no roles'}]; signing licence terms needs rights_reviewer or clinical_lead"
        )
    return row["id"]


def cmd_sign(conn: psycopg.Connection, args: argparse.Namespace) -> int:
    try:
        if args.reject and not args.note:
            raise PolicyError("rejecting a publisher needs --note saying why; an unexplained refusal gets re-proposed next quarter")
        reviewer = _reviewer_id(conn, args.reviewer)
        row = reject(conn, args.domain, reviewer, args.note) if args.reject else sign(conn, args.domain, reviewer, args.note)
    except PolicyError as e:
        conn.rollback()
        print(f"refused: {e}", file=sys.stderr)
        return 2
    conn.commit()
    verb = "rejected" if args.reject else "signed"
    print(f"{verb} {row['domain']} ({row['publisher']}, {row['license_id']}) by {args.reviewer}")
    if not args.reject:
        print(f"readable: {'yes' if row['effective'] else 'no'}")
        if not row["effective"]:
            print(f"  the licence permits can_fetch={row['can_fetch']}, so this publisher still cannot be read.")
        print(f"  next review: {row['next_review_at']:%Y-%m-%d}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Manage the curated source allowlist.")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("load", help="read the policy files into the database")

    cap = sub.add_parser("capture", help="fetch each publisher's terms page and record it (needs internet access)")
    cap.add_argument("--domain", default=None, help="just this one")

    sub.add_parser("list", help="show every publisher and what it is waiting for")

    ft = sub.add_parser("find-terms", help="list candidate terms pages for publishers whose URL did not resolve")
    ft.add_argument("--domain", default=None, help="just this one")
    ft.add_argument("--all", action="store_true", help="include publishers whose terms were already captured")

    sg = sub.add_parser("sign", help="accept or reject a publisher's captured terms")
    sg.add_argument("--domain", required=True)
    sg.add_argument("--reviewer", required=True, help="email of a rights_reviewer or clinical_lead")
    sg.add_argument("--note", default=None, help="recorded with the decision")
    sg.add_argument("--reject", action="store_true", help="record a decision not to use this publisher")

    args = ap.parse_args(argv)
    handlers = {"load": cmd_load, "capture": cmd_capture, "list": cmd_list, "sign": cmd_sign, "find-terms": cmd_find_terms}
    with connect() as conn:
        conn.row_factory = dict_row
        return handlers[args.cmd](conn, args)


if __name__ == "__main__":
    sys.exit(main())
